# Configurare conexiune PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/florarie_db
spring.datasource.username=postgres
spring.datasource.password=florarie
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate creeaza/actualizeaza automat tabelele pe baza entitatilor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
